# -*- coding: utf-8 -*-
"""Artwork data and UI strings in both languages."""

# (title, medium, description, alt) per language; shared: category + thumb size
ART = {
 1: dict(cat="portrait", w=1275, h=1800,
   en=("Carried", "Watercolour",
       "A painting close to the artist's heart — begun in Thailand and completed in Germany before travelling on to New Zealand for the start of a PhD. “I have carried this painting wherever I go, and each time I see it, it reminds me to keep practicing art.”",
       "Watercolour portrait of a mother carrying her child on her back in a plaid woven wrap"),
   de=("Getragen", "Aquarell",
       "Ein Bild, das der Künstlerin besonders am Herzen liegt — in Thailand begonnen, in Deutschland vollendet und danach nach Neuseeland mitgenommen, zum Beginn einer Promotion. „Ich habe dieses Bild überallhin mitgenommen, und jedes Mal, wenn ich es sehe, erinnert es mich daran, weiterzumalen.“",
       "Aquarellporträt einer Mutter, die ihr Kind in einem karierten Tuch auf dem Rücken trägt")),
 2: dict(cat="portrait", w=1275, h=1800,
   en=("Winter Smile", "Watercolour",
       "A child grinning out from under a knitted cap, bundled in red against the snow and the open sky behind.",
       "Watercolour portrait of a smiling child in a knitted hat and red clothing in a snowy landscape"),
   de=("Winterlächeln", "Aquarell",
       "Ein Kind, das unter einer Strickmütze hervorlacht, dick in Rot eingepackt, hinter sich Schnee und offener Himmel.",
       "Aquarellporträt eines lachenden Kindes mit Strickmütze und roter Kleidung in verschneiter Landschaft")),
 3: dict(cat="portrait", w=1275, h=1800,
   en=("Honey Hunters of Nepal", "Acrylic on 180gsm paper, A3",
       "Begun in February 2022 and completed over a year and a half later, referenced from a documentary cover photo by a French journalist. “I was captivated by the intensity in their eyes, the fearless expression on their faces, and their unwavering courage.”",
       "Painting of two honey hunters of Nepal on a rock, one standing with a pole and one crouching"),
   de=("Die Honigjäger Nepals", "Acryl auf 180-g-Papier, A3",
       "Im Februar 2022 begonnen und erst anderthalb Jahre später vollendet, nach dem Titelfoto einer Dokumentation eines französischen Journalisten. „Mich hat die Intensität in ihren Augen gefesselt, der furchtlose Ausdruck in ihren Gesichtern und ihr unerschütterlicher Mut.“",
       "Gemälde zweier nepalesischer Honigjäger auf einem Felsen, einer stehend mit Stange, einer hockend")),
 4: dict(cat="portrait", w=1275, h=1800,
   en=("Butter Tea", "Acrylic",
       "An older man in saffron pauses over a bowl held in both hands — prayer beads, long hair, and a face weathered by altitude.",
       "Acrylic portrait of an older man in an orange robe drinking from a bowl held in both hands"),
   de=("Buttertee", "Acryl",
       "Ein älterer Mann in Safrangelb hält inne über einer Schale in beiden Händen — Gebetskette, langes Haar und ein vom Höhenklima gezeichnetes Gesicht.",
       "Acrylporträt eines älteren Mannes in orangefarbenem Gewand, der aus einer Schale in beiden Händen trinkt")),
 5: dict(cat="still-life", w=1273, h=1800,
   en=("Tulips in a Glass", "Acrylic",
       "Red tulips leaning out of a plain drinking glass, painted loosely against a wash of spring blue.",
       "Acrylic still life of red tulips in a clear glass against a blue background"),
   de=("Tulpen im Glas", "Acryl",
       "Rote Tulpen, die sich aus einem einfachen Trinkglas neigen, locker gemalt vor einem Frühlingsblau.",
       "Acryl-Stillleben mit roten Tulpen in einem Glas vor blauem Hintergrund")),
 6: dict(cat="portrait", w=1275, h=1800,
   en=("Waiting", "Watercolour & mixed media",
       "The second time the artist has returned to this scene: a goat consoling a child who is home alone, waiting for her mother to return. “I can never get enough of this picture.”",
       "Painting of a young child in a red dress comforted by a white goat in a doorway"),
   de=("Warten", "Aquarell und Mischtechnik",
       "Zum zweiten Mal ist die Künstlerin zu dieser Szene zurückgekehrt: eine Ziege tröstet ein Kind, das allein zu Hause auf die Mutter wartet. „Von diesem Bild bekomme ich einfach nicht genug.“",
       "Gemälde eines kleinen Kindes im roten Kleid, das von einer weißen Ziege im Türrahmen getröstet wird")),
 7: dict(cat="landscape", w=1275, h=1800,
   en=("Street at Dusk", "Watercolour",
       "Tram wires strung across a European street as the evening sky turns coral above the rooftops.",
       "Watercolour of a European city street with tram wires and coral clouds at sunset"),
   de=("Straße in der Dämmerung", "Aquarell",
       "Straßenbahnleitungen spannen sich über eine Straße, während der Abendhimmel über den Dächern korallenrot wird.",
       "Aquarell einer europäischen Straße mit Oberleitungen und korallenroten Wolken bei Sonnenuntergang")),
 8: dict(cat="portrait", w=1275, h=1800,
   en=("Adorned", "Acrylic",
       "A portrait built around silver — headdress, choker, and the steady, unblinking gaze beneath them.",
       "Portrait of a woman wearing an ornate silver headdress and choker with dark curled hair"),
   de=("Geschmückt", "Acryl",
       "Ein Porträt, das um Silber herum gebaut ist — Kopfschmuck, Halsreif und darunter ein ruhiger, unverwandter Blick.",
       "Porträt einer Frau mit reich verziertem Silberkopfschmuck und Halsreif, mit dunklem lockigem Haar")),
 9: dict(cat="portrait", w=1275, h=1800,
   en=("Carrying Rhododendrons", "Acrylic on canvas",
       "A girl steadies a doko basket heavy with lali gurans, caught mid-step on the walk home.",
       "Painting of a girl carrying a woven basket filled with red rhododendron branches"),
   de=("Mit Rhododendren", "Acryl auf Leinwand",
       "Ein Mädchen stützt einen Doko-Korb voller Lali Gurans, mitten im Schritt auf dem Heimweg.",
       "Gemälde eines Mädchens, das einen Korbtragekorb voller roter Rhododendronzweige trägt")),
 10: dict(cat="landscape", w=1275, h=1800,
   en=("Evening Sky I", "Watercolour",
       "A small study of dusk — lit windows appearing one by one beneath a sky still burning at the edges.",
       "Small watercolour study of a city skyline at sunset with lit windows"),
   de=("Abendhimmel I", "Aquarell",
       "Eine kleine Dämmerungsstudie — erleuchtete Fenster gehen nacheinander an unter einem Himmel, der an den Rändern noch brennt.",
       "Kleine Aquarellstudie einer Stadtsilhouette bei Sonnenuntergang mit erleuchteten Fenstern")),
 11: dict(cat="landscape", w=1275, h=1800,
   en=("Evening Sky II", "Watercolour",
       "The same hour, painted again — banks of cloud catching fire above a low, darkening skyline.",
       "Watercolour of red and orange sunset clouds above a dark rooftop skyline"),
   de=("Abendhimmel II", "Aquarell",
       "Dieselbe Stunde, noch einmal gemalt — Wolkenbänke fangen Feuer über einer flachen, dunkler werdenden Skyline.",
       "Aquarell mit roten und orangefarbenen Abendwolken über einer dunklen Dächerlandschaft")),
 12: dict(cat="landscape", w=1275, h=1800,
   en=("Corner House", "Acrylic",
       "An orange corner block under a big, moving sky — a quiet street painted from an upstairs window.",
       "Acrylic painting of an orange corner building on a street beneath a cloudy blue sky"),
   de=("Das Eckhaus", "Acryl",
       "Ein oranger Eckbau unter einem großen, bewegten Himmel — eine ruhige Straße, aus einem Fenster im Obergeschoss gemalt.",
       "Acrylgemälde eines orangefarbenen Eckhauses an einer Straße unter bewölktem blauem Himmel")),
 13: dict(cat="landscape", w=1275, h=1800,
   en=("Sky on Fire", "Acrylic",
       "A bare winter tree held against a sunset that fills the whole upper half of the paper.",
       "Acrylic painting of a bare tree silhouetted against a fiery red and orange sunset over buildings"),
   de=("Brennender Himmel", "Acryl",
       "Ein kahler Winterbaum vor einem Sonnenuntergang, der die ganze obere Blatthälfte einnimmt.",
       "Acrylgemälde eines kahlen Baums als Silhouette vor einem feuerroten Sonnenuntergang über Häusern")),
 14: dict(cat="landscape", w=1275, h=1800,
   en=("Milky Way", "Watercolour",
       "Pines cut black against the galaxy, with the last of the sunset still glowing along the horizon.",
       "Watercolour of the Milky Way over silhouetted pine trees with a pink horizon"),
   de=("Milchstraße", "Aquarell",
       "Schwarze Kiefern vor der Galaxie, am Horizont glüht der letzte Rest des Sonnenuntergangs.",
       "Aquarell der Milchstraße über Kiefernsilhouetten mit rosafarbenem Horizont")),
 15: dict(cat="portrait", w=1275, h=1800,
   en=("In the Doorway", "Pastel",
       "Two figures pausing at a threshold, drawn in soft pastel on a sun-warmed ochre wall.",
       "Pastel drawing of a man and a woman in a red headscarf standing beside a dark doorway"),
   de=("Im Türrahmen", "Pastell",
       "Zwei Gestalten, die an einer Schwelle innehalten, in weichem Pastell auf sonnenwarmem Ockergelb.",
       "Pastellzeichnung eines Mannes und einer Frau mit rotem Kopftuch neben einem dunklen Türrahmen")),
 16: dict(cat="portrait", w=1275, h=1800,
   en=("Laughter", "Acrylic on canvas",
       "A woman caught mid-laugh, eyes closed, coral and pearl at her throat — a portrait about joy more than likeness.",
       "Portrait of a laughing woman wearing red coral and white pearl necklaces"),
   de=("Lachen", "Acryl auf Leinwand",
       "Eine Frau mitten im Lachen, die Augen geschlossen, Korallen und Perlen am Hals — ein Porträt, in dem es mehr um Freude geht als um Ähnlichkeit.",
       "Porträt einer lachenden Frau mit roten Korallen- und weißen Perlenketten")),
 17: dict(cat="portrait", w=1275, h=1800,
   en=("The Green Dress", "Acrylic & watercolour",
       "Embroidery, mirrorwork and silver rendered thread by thread around a calm, direct gaze.",
       "Portrait of a woman in an embroidered green and orange dress with silver jewellery and long braids"),
   de=("Das grüne Kleid", "Acryl und Aquarell",
       "Stickerei, Spiegelarbeit und Silber, Faden für Faden ausgeführt, um einen ruhigen, direkten Blick herum.",
       "Porträt einer Frau in einem bestickten grün-orangen Kleid mit Silberschmuck und langen Zöpfen")),
 18: dict(cat="landscape", w=1275, h=1800,
   en=("Red Roofs", "Watercolour",
       "Tiled rooftops climbing towards a green copper dome — an old European city seen from above.",
       "Watercolour of red tiled rooftops and a green copper dome in an old European city"),
   de=("Rote Dächer", "Aquarell",
       "Ziegeldächer, die zu einer grünen Kuppel hinaufsteigen — eine alte europäische Stadt von oben gesehen.",
       "Aquarell roter Ziegeldächer und einer grünen Kupferkuppel in einer alten europäischen Stadt")),
 19: dict(cat="still-life", w=1114, h=1241,
   en=("Two Pots", "Watercolour",
       "Pansies and lavender sharing a blue bistro table, painted in a single quiet sitting.",
       "Watercolour of two terracotta pots of pansies and lavender on a blue garden table"),
   de=("Zwei Töpfe", "Aquarell",
       "Stiefmütterchen und Lavendel teilen sich einen blauen Bistrotisch, in einer einzigen ruhigen Sitzung gemalt.",
       "Aquarell mit zwei Terrakottatöpfen mit Stiefmütterchen und Lavendel auf einem blauen Gartentisch")),
 20: dict(cat="still-life", w=1178, h=1187,
   en=("Poppies, Study", "Watercolour sketchbook",
       "A sketchbook study of poppies, made while the artist was studying the work of painter Thomas Braun and his admiration for Monet. “His way of thinking about painting felt honest, generous, and perspective-shifting.”",
       "Watercolour sketchbook study of red poppies and seed heads"),
   de=("Mohnblumen, Studie", "Aquarell, Skizzenbuch",
       "Eine Skizzenbuchstudie von Mohnblumen, entstanden, während sich die Künstlerin mit dem Werk des Malers Thomas Braun und seiner Bewunderung für Monet beschäftigte. „Seine Art, über Malerei nachzudenken, war ehrlich, großzügig und hat meinen Blick verändert.“",
       "Aquarell-Skizzenbuchstudie mit rotem Mohn und Samenkapseln")),
 21: dict(cat="still-life", w=1122, h=1170,
   en=("Window Box", "Watercolour",
       "Dark pansies crowding a terracotta trough set into a cool stone window ledge.",
       "Watercolour of purple pansies in a terracotta window box on a stone ledge"),
   de=("Blumenkasten", "Aquarell",
       "Dunkle Stiefmütterchen drängen sich in einem Terrakottakasten auf einer kühlen steinernen Fensterbank.",
       "Aquarell mit violetten Stiefmütterchen in einem Terrakotta-Blumenkasten auf einer Steinbank")),
 22: dict(cat="landscape", w=1725, h=1102,
   en=("Home Below the Mountains", "Acrylic",
       "A thatched house among banana palms, with the snow peaks standing over the valley behind it.",
       "Acrylic painting of a thatched Nepali house among green palms with snow mountains behind"),
   de=("Zuhause unter den Bergen", "Acryl",
       "Ein strohgedecktes Haus zwischen Bananenstauden, dahinter stehen die Schneegipfel über dem Tal.",
       "Acrylgemälde eines strohgedeckten nepalesischen Hauses zwischen grünen Palmen mit Schneebergen dahinter")),
 23: dict(cat="still-life", w=1275, h=1800,
   en=("Berries Against the Sky", "Acrylic",
       "Looking straight up through a berry-laden branch into a clouded blue — painted from below.",
       "Acrylic painting of red berries and green foliage against a blue and white sky"),
   de=("Beeren vor dem Himmel", "Acryl",
       "Der Blick geht senkrecht nach oben durch einen beerenschweren Zweig ins bewölkte Blau — von unten gemalt.",
       "Acrylgemälde mit roten Beeren und grünem Laub vor blau-weißem Himmel")),
 24: dict(cat="still-life", w=1275, h=1800,
   en=("Wildflowers", "Watercolour",
       "A handful of garden flowers dropped into a coiled clay vase, loose and unfussed.",
       "Watercolour of small wildflowers in a coiled pink clay vase"),
   de=("Wiesenblumen", "Aquarell",
       "Eine Handvoll Gartenblumen, locker und ungekünstelt in eine gewundene Tonvase gestellt.",
       "Aquarell mit kleinen Wiesenblumen in einer gewundenen rosa Tonvase")),
 25: dict(cat="portrait", w=1510, h=1545,
   en=("Softness that Endures", "Acrylic on canvas",
       "This is an old woman from Bhaktapur, an ancient city in Nepal. I was drawn to her face — the wrinkles, the expression, the grey hair. To me, her face carries a whole lifetime of stories and experiences. I am from Nepal, so these faces and these gestures are part of the visual world I grew up with. Bhaktapur has a very distinctive cultural character, and I wanted to bring a small piece of that world into this European art space.",
       "Painting of an elderly woman from Bhaktapur with grey hair, her cupped hands raised to her face as she smokes"),
   de=("Sanftheit die bleibt", "Acryl auf Leinwand",
       "Dies ist eine alte Frau aus Bhaktapur, einer alten Stadt in Nepal. Ihr Gesicht hat mich angezogen — die Falten, der Ausdruck, das graue Haar. Für mich trägt dieses Gesicht ein ganzes Leben voller Geschichten und Erfahrungen. Ich komme aus Nepal; diese Gesichter und diese Gesten gehören zu der Bilderwelt, in der ich aufgewachsen bin. Bhaktapur hat einen ganz eigenen kulturellen Charakter, und ich wollte ein kleines Stück dieser Welt in diesen europäischen Kunstraum bringen.",
       "Gemälde einer alten Frau aus Bhaktapur mit grauem Haar, die ihre hohlen Hände zum Gesicht führt und raucht")),
}

ORDER = [25, 3, 1, 16, 6, 9, 4, 13, 17, 22, 2, 7, 8, 14, 5, 18, 15, 23, 11, 20, 12, 19, 10, 24, 21]


# ---------------------------------------------------------------- UI strings
S = {
"en": dict(
  html_lang="en",
  skip="Skip to content",
  nav_about="About", nav_gallery="Gallery", nav_exh="Exhibitions", nav_contact="Contact",
  lang_switch_label="Diese Seite auf Deutsch", lang_switch_text="DE", lang_switch_name="Deutsch",
  theme_label="Switch between light and dark mode",
  cat={"portrait": "Portraits", "landscape": "Landscapes", "still-life": "Still Life"},
  filter_all="All",
  enquire="Enquire about this piece",
  see_exhibition="See it on exhibition",
  badge_exhibited="On exhibition",
  lb_close="Close", lb_prev="Previous artwork", lb_next="Next artwork",
  lb_photo_prev="Previous photo", lb_photo_next="Next photo",
  viewer="Artwork viewer", photo_viewer="Photo viewer",
  view_larger="View {t} larger",
  foot_home="Home", foot_exh="Exhibitions", foot_email="Email",
  foot_rights="All artwork shown remains the property of the artist.",
  breadcrumb_home="Home",
  # contact block
  contact_h="Commissions, prices &amp; enquiries",
  contact_p="Every painting on this site is an original, and most are available. Prices depend on size, medium and whether the piece is framed — write with the title you're interested in and you'll get a quote, usually within a couple of days.",
  contact_btn="Email Srijana", contact_prints="Prints on Etsy",
  # index
  meta_title="Srijana GS — Artist",
  meta_desc="Original paintings by Srijana GS — portraits, landscapes and still life in acrylic and watercolour, made between Nepal and Leipzig. Works available; prices on request.",
  hero_kicker="Painter · Leipzig, Germany",
  hero_lede="Self-taught artist working in acrylic and watercolor — painting faces, memory, and quiet moments carried between Nepal, and every place life has taken her since.",
  hero_cta1="View the gallery", hero_cta2="Where to see the work",
  about_kicker="About the artist",
  about_h="Painting as a way of looking closely",
  about_p1="Srijana is a self-taught artist who paints in acrylic, watercolor, and mixed media — portraits of people she encounters through photographs, memory, and travel, alongside landscapes and quiet still life studies of flowers she's grown or gathered along the way.",
  about_p2="Her portraits often return to faces that carry a story: honey hunters from the mountains of Nepal, mothers carrying children through the cold, a child comforted by an animal while waiting for someone to come home. She's drawn to expressions that hold both hardship and quiet dignity.",
  about_quote="\"Painting has always served as my inner world — allowing me to dive in and sit with the characters I paint.\"",
  about_p3="One painting travelled with her from Thailand to Germany, and on to New Zealand before a PhD — carried along not because it was finished, but because, as she puts it, finishing a piece can feel like its own quiet grief. She's currently based in Leipzig, Germany, still learning — most recently inspired by the work of painter Thomas Braun and a growing love for Impressionism.",
  fact1="Works shown", fact2_n="Nepal → Thailand → New Zealand → Germany", fact2="Journey", fact3_n="Self-taught", fact3="Practice",
  about_photo_alt="Srijana sitting on the floor of her Leipzig studio, palette in hand, working at the easel on the large portrait of the woman from Bhaktapur",
  gal_kicker="Selected work", gal_h="Gallery",
  gal_p="Twenty-five paintings — portraits, landscapes, and still life studies. Click any piece to see it larger.",
  avail="<strong>Most of these paintings are available.</strong> Prices aren't listed because they depend on size, medium and framing — open any piece and use <em>Enquire about this piece</em>, and Srijana will come back to you with a price, usually within a couple of days.",
  proc_kicker="In the studio", proc_h="On finishing a painting",
  proc_q1="\"There is this particular kind of sadness or grief wherever I finish a painting. It feels like the end of something — like the end of intimacy, closing the door, letting go.\"",
  proc_q2="\"Maybe it's because I find the beauty in the process more than the final output — in the becoming, in the possibilities and uncertainty of an incomplete work.\"",
  proc_sig="— Srijana, from her studio in Leipzig",
  # exhibitions index
  exh_title="Exhibitions — Srijana GS",
  exh_desc="Where to see Srijana GS's paintings in person: the open-air gallery Am Kunstwinkel in Markkleeberg, and upcoming markets and exhibitions around Leipzig.",
  exh_kicker="Exhibitions &amp; markets", exh_h="Where to see the work",
  exh_lede="Paintings shown in public, past and upcoming. Some pieces travel; if you want to see a particular painting in person, just ask.",
  pill_up="Upcoming", pill_live="On show until 2027",
  go_details="Event details →", go_details_bid="Event details &amp; bidding →",
  card_go_h="Kunstmarkt, Garage Ost",
  card_go_when="Saturday 12 September 2026 · 13:00–16:00",
  card_go_p="A table of her own at the Kunstmarkt in Garage Ost — originals, studies and prints, and the chance to talk to her about a commission in person.",
  card_kw_h="Am Kunstwinkel — “Mein Bild für Dich”",
  card_kw_when="From 5 September 2026 · Markkleeberg",
  card_kw_p="“Softness that Endures” was selected as one of 24 works for the open-air gallery wall in Markkleeberg. It hangs there for a year, then goes to auction.",
  exh_cta="<strong>Organising something?</strong> Srijana is open to markets, group shows and café or practice exhibitions in and around Leipzig. Write to <a href=\"mailto:{email}\">{email}</a>.",
),
"de": dict(
  html_lang="de",
  skip="Zum Inhalt springen",
  nav_about="Über mich", nav_gallery="Galerie", nav_exh="Ausstellungen", nav_contact="Kontakt",
  lang_switch_label="This page in English", lang_switch_text="EN", lang_switch_name="English",
  theme_label="Zwischen hellem und dunklem Modus wechseln",
  cat={"portrait": "Porträts", "landscape": "Landschaften", "still-life": "Stillleben"},
  filter_all="Alle",
  enquire="Nach diesem Bild fragen",
  see_exhibition="In der Ausstellung sehen",
  badge_exhibited="Ausgestellt",
  lb_close="Schließen", lb_prev="Vorheriges Werk", lb_next="Nächstes Werk",
  lb_photo_prev="Vorheriges Foto", lb_photo_next="Nächstes Foto",
  viewer="Bildansicht", photo_viewer="Fotoansicht",
  view_larger="{t} größer ansehen",
  foot_home="Startseite", foot_exh="Ausstellungen", foot_email="E-Mail",
  foot_rights="Alle gezeigten Werke bleiben Eigentum der Künstlerin.",
  breadcrumb_home="Startseite",
  contact_h="Auftragsarbeiten, Preise &amp; Anfragen",
  contact_p="Jedes Bild auf dieser Seite ist ein Original, und die meisten sind verfügbar. Der Preis hängt von Größe, Technik und Rahmung ab — schreiben Sie einfach mit dem Titel des Bildes, das Sie interessiert, und Sie bekommen in der Regel innerhalb von zwei Tagen eine Antwort.",
  contact_btn="Srijana schreiben", contact_prints="Drucke auf Etsy",
  meta_title="Srijana GS — Künstlerin in Leipzig",
  meta_desc="Originalgemälde von Srijana GS — Porträts, Landschaften und Stillleben in Acryl und Aquarell, entstanden zwischen Nepal und Leipzig. Werke verfügbar, Preise auf Anfrage.",
  hero_kicker="Malerin · Leipzig",
  hero_lede="Autodidaktische Künstlerin, die in Acryl und Aquarell arbeitet — Gesichter, Erinnerungen und stille Augenblicke, mitgenommen aus Nepal und aus jedem Ort, an den das Leben sie seitdem geführt hat.",
  hero_cta1="Zur Galerie", hero_cta2="Wo die Bilder zu sehen sind",
  about_kicker="Über die Künstlerin",
  about_h="Malen als eine Art, genau hinzusehen",
  about_p1="Srijana ist eine autodidaktische Künstlerin und arbeitet in Acryl, Aquarell und Mischtechnik — Porträts von Menschen, denen sie über Fotografien, Erinnerungen und auf Reisen begegnet, daneben Landschaften und stille Stillleben von Blumen, die sie selbst gezogen oder unterwegs gesammelt hat.",
  about_p2="Ihre Porträts kehren immer wieder zu Gesichtern zurück, die eine Geschichte tragen: Honigjäger aus den Bergen Nepals, Mütter, die ihre Kinder durch die Kälte tragen, ein Kind, das von einem Tier getröstet wird, während es auf jemanden wartet. Sie sucht Ausdrücke, in denen Härte und stille Würde zugleich liegen.",
  about_quote="„Das Malen war für mich immer eine innere Welt — ich kann darin eintauchen und bei den Figuren bleiben, die ich male.“",
  about_p3="Ein Bild reiste mit ihr von Thailand nach Deutschland und weiter nach Neuseeland, vor einer Promotion — mitgenommen nicht, weil es fertig war, sondern weil, wie sie sagt, das Fertigwerden eines Bildes sich wie eine eigene stille Trauer anfühlen kann. Heute lebt sie in Leipzig und lernt weiter — zuletzt inspiriert von der Arbeit des Malers Thomas Braun und einer wachsenden Liebe zum Impressionismus.",
  fact1="Gezeigte Werke", fact2_n="Nepal → Thailand → Neuseeland → Deutschland", fact2="Weg", fact3_n="Autodidaktin", fact3="Arbeitsweise",
  about_photo_alt="Srijana sitzt auf dem Boden ihres Leipziger Ateliers, die Palette in der Hand, und arbeitet an der Staffelei an dem großen Porträt der Frau aus Bhaktapur",
  gal_kicker="Ausgewählte Arbeiten", gal_h="Galerie",
  gal_p="Fünfundzwanzig Bilder — Porträts, Landschaften und Stillleben. Klicken Sie auf ein Werk, um es größer zu sehen.",
  avail="<strong>Die meisten dieser Bilder sind verfügbar.</strong> Preise stehen nicht dabei, weil sie von Größe, Technik und Rahmung abhängen — öffnen Sie ein Bild und klicken Sie auf <em>Nach diesem Bild fragen</em>, dann meldet sich Srijana in der Regel innerhalb von zwei Tagen mit einem Preis.",
  proc_kicker="Im Atelier", proc_h="Über das Fertigwerden eines Bildes",
  proc_q1="„Da ist diese besondere Art von Traurigkeit, wann immer ich ein Bild beende. Es fühlt sich an wie das Ende von etwas — wie das Ende einer Nähe, wie eine Tür, die zugeht.“",
  proc_q2="„Vielleicht liegt es daran, dass ich die Schönheit mehr im Prozess finde als im Ergebnis — im Werden, in den Möglichkeiten und der Ungewissheit eines unfertigen Bildes.“",
  proc_sig="— Srijana, aus ihrem Atelier in Leipzig",
  exh_title="Ausstellungen — Srijana GS",
  exh_desc="Wo die Bilder von Srijana GS zu sehen sind: die Freiluftgalerie Am Kunstwinkel in Markkleeberg und kommende Märkte und Ausstellungen in und um Leipzig.",
  exh_kicker="Ausstellungen &amp; Märkte", exh_h="Wo die Bilder zu sehen sind",
  exh_lede="Öffentlich gezeigte Arbeiten, vergangene und kommende. Manche Bilder sind unterwegs; wenn Sie ein bestimmtes Werk in echt sehen möchten, fragen Sie einfach.",
  pill_up="Demnächst", pill_live="Zu sehen bis 2027",
  go_details="Zur Veranstaltung →", go_details_bid="Veranstaltung &amp; Versteigerung →",
  card_go_h="Kunstmarkt, Garage Ost",
  card_go_when="Samstag, 12. September 2026 · 13:00–16:00 Uhr",
  card_go_p="Ein eigener Tisch beim Kunstmarkt in der Garage Ost — Originale, Studien und Drucke, und die Gelegenheit, persönlich über eine Auftragsarbeit zu sprechen.",
  card_kw_h="Am Kunstwinkel — „Mein Bild für Dich“",
  card_kw_when="Ab 5. September 2026 · Markkleeberg",
  card_kw_p="„Sanftheit die bleibt“ wurde als eines von 24 Werken für die Freiluftgalerie in Markkleeberg ausgewählt. Ein Jahr lang hängt das Bild dort, danach wird es versteigert.",
  exh_cta="<strong>Sie organisieren etwas?</strong> Srijana freut sich über Märkte, Gruppenausstellungen und Ausstellungen in Cafés oder Praxen in und um Leipzig. Schreiben Sie an <a href=\"mailto:{email}\">{email}</a>.",
),
}

# en file  ->  de file
PAGE_FILES = {
    "index":       ("index.html",                     "index.html"),
    "exhibitions": ("exhibitions.html",               "ausstellungen.html"),
    "kunstwinkel": ("exhibition-kunstwinkel.html",    "ausstellung-kunstwinkel.html"),
    "garageost":   ("exhibition-garage-ost.html",     "ausstellung-garage-ost.html"),
    "impressum":   ("impressum.html",                 "impressum.html"),
    "datenschutz": ("datenschutz.html",               "datenschutz.html"),
}


# ---------------------------------------------------- event & legal page copy
S["en"].update(
  kw_title="Am Kunstwinkel, Markkleeberg 2026/27 — Srijana GS",
  kw_desc="“Softness that Endures” by Srijana GS is one of 24 works in the open-air gallery Am Kunstwinkel in Markkleeberg, on show until 2027 and then auctioned.",
  kw_pill="On show until autumn 2027",
  kw_h="Am Kunstwinkel, Markkleeberg",
  kw_lede="“Softness that Endures” was selected as one of 24 works for the 2026/27 open-air gallery on the Kunstwinkel wall, under the motto <em>“Mein Bild für Dich”</em>. It was unveiled at the 8th Kunstwinkelfest on 5 September 2026 and hangs there for a full year.",
  kw_work_p="“This is an old woman from Bhaktapur, an ancient city in Nepal. I was drawn to her face — the wrinkles, the expression, the grey hair. To me, her face carries a whole lifetime of stories and experiences. Bhaktapur has a very distinctive cultural character, and I wanted to bring a small piece of that world into this European art space.”",
  kw_see_gallery="See it in the gallery",
  kw_how_h="How this one works",
  kw_how_p="The Kunstwinkel is a permanent open-air gallery on a house wall at Rathausstraße 23 in Markkleeberg. Each year the town selects 24 works from submitted artists, mounts them on the wall for twelve months, and then auctions them at the following year's Kunstwinkelfest — with the proceeds going to the artists and the project.",
  kw_f_exh="Exhibition", kw_f_exh_v="Am Kunstwinkel — open-air gallery, 2026/27 collection",
  kw_f_motto="Motto", kw_f_work="Work shown",
  kw_f_unveiled="Unveiled", kw_f_unveiled_v="5 September 2026, at the 8th Kunstwinkelfest",
  kw_f_until="On show until", kw_f_until_v="Kunstwinkelfest 2027",
  kw_f_where="Where", kw_f_selected="Selected works", kw_f_selected_v="24, by 24 different artists",
  kw_f_org="Organiser", kw_f_org_v="Stadt Markkleeberg",
  kw_bid_h="Bidding is not open yet.",
  kw_bid_p1="The 2026/27 collection — the one this painting belongs to — goes to auction at the Kunstwinkelfest in September 2027. The town publishes an online catalogue a few weeks beforehand, run by the auction house IKV Fester, where bids can be placed in advance of the live auction.",
  kw_bid_p2="This page will carry the direct bidding link as soon as the town publishes it. Until then:",
  kw_bid_b1="Kunstwinkelfest page", kw_bid_b2="Auction house",
  kw_alt_p="If you'd rather not wait for the auction, Srijana has other originals available directly — <a href=\"{gallery}#gallery\">see the gallery</a> or <a href=\"mailto:{email}?subject=Painting%20enquiry\">write to her</a>.",
  kw_film_kicker="5 September 2026", kw_film_h="On the day",
  kw_film_p="A few seconds at the 8th Kunstwinkelfest — the camera lifts from the artist to the wall, where her painting hangs in the top row.",
  kw_film_cap="Srijana at Am Kunstwinkel, 5 September 2026.",
  kw_film_fallback="Your browser can't play this video.",
  kw_film_download="Download it instead",
  kw_photos_h="The unveiling",
  kw_photos_p="The 8th Kunstwinkelfest, when the new collection went up on the wall.",
  kw_alt_board="The open-air gallery wall at Am Kunstwinkel, Markkleeberg, with the 24 newly unveiled works",
  kw_alt_artist_wall="Srijana in front of the Kunstwinkel wall on the day of the unveiling",
  kw_alt_detail="Close view of the wall showing “Softness that Endures” among the neighbouring works",
  kw_alt_lettering="The Am Kunstwinkel lettering above the mounted collection of 24 works",
  kw_alt_wide="The gable wall at Am Kunstwinkel with the mounted open-air gallery beneath the lettering",
  kw_alt_artist="Srijana at the Kunstwinkelfest",
  kw_alt_angle="The gallery wall seen from the side, with the painted lake mural below",
  kw_alt_artist_full="Srijana beneath the Am Kunstwinkel lettering",
  # --- Garage Ost
  go_title="Kunstmarkt, Garage Ost Leipzig — Srijana GS",
  go_desc="Srijana GS shows and sells original paintings at her own table at the Kunstmarkt in Garage Ost, Leipzig — Saturday 12 September 2026, 13:00–16:00.",
  go_h="Kunstmarkt at Garage Ost",
  go_lede="One afternoon in Leipzig with the originals on the table — the paintings from this website, some studies that never made it online, and the chance to talk about a commission face to face.",
  go_poster_alt="Kunstmarkt poster from Garage Ost — a market stall of prints, ceramics and framed artwork",
  go_poster_credit="Event poster: Garage Ost.",
  go_come_h="Come and say hello",
  go_p1="Srijana will have her own table, showing original paintings and smaller works on paper. Everything on the table is for sale, and there is no obligation at all — it's just as good a reason to come and look closely at the brushwork, ask how a piece was made, or talk about a portrait of someone in your own family.",
  go_p2="If there's a particular painting from the <a href=\"{gallery}#gallery\">gallery</a> you'd like to see in person, <a href=\"mailto:{email}?subject=Garage%20Ost%20-%20can%20you%20bring%20a%20painting%3F\">send a message beforehand</a> and she'll bring it along.",
  go_f_event="Event", go_f_event_v="Kunstmarkt — Srijana's table: original paintings, studies and prints",
  go_f_date="Date", go_f_date_v="Saturday, 12 September 2026",
  go_f_time="Time", go_f_time_v="13:00 – 16:00",
  go_f_venue="Venue", go_f_addr="Address", go_f_addr_v="Hermann-Liebmann-Straße 65–67, 04315 Leipzig",
  go_f_entry="Entry", go_f_entry_v="Free",
  go_f_pay="Payment", go_f_pay_v="Cash, or bank transfer by arrangement",
  go_note="<strong>Date still to be confirmed.</strong> The venue is fixed; the exact date and time follow the organiser's listing. Follow <a href=\"{insta}\" target=\"_blank\" rel=\"noopener\">@srijana.art.gallery</a>, or <a href=\"mailto:{email}?subject=Garage%20Ost%20details\">ask by email</a>. The listing is on <a href=\"{listing}\" target=\"_blank\" rel=\"noopener\">rausgegangen.de</a>.",
  go_table_h="What's likely to be on the table",
  go_table_medium="Originals · studies · prints",
  go_table_p="A mix of the portraits and the smaller watercolour studies — the sketchbook pieces are the easiest place to start a collection, and the large acrylic portraits are the ones people tend to stand in front of longest.",
  go_browse="Browse the gallery first",
  # --- legal
  imp_title="Impressum — Srijana GS", imp_desc="Legal notice (Impressum) for srijana-art.github.io according to § 5 DDG.",
  ds_title="Datenschutzerklärung — Srijana GS", ds_desc="Privacy notice for srijana-art.github.io.",
)

S["de"].update(
  kw_title="Am Kunstwinkel, Markkleeberg 2026/27 — Srijana GS",
  kw_desc="„Sanftheit die bleibt“ von Srijana GS ist eines von 24 Werken der Freiluftgalerie Am Kunstwinkel in Markkleeberg — zu sehen bis 2027, danach Versteigerung.",
  kw_pill="Zu sehen bis Herbst 2027",
  kw_h="Am Kunstwinkel, Markkleeberg",
  kw_lede="„Sanftheit die bleibt“ wurde als eines von 24 Werken für die Freiluftgalerie 2026/27 an der Kunstwinkel-Wand ausgewählt, unter dem Motto <em>„Mein Bild für Dich“</em>. Enthüllt wurde die Sammlung beim 8. Kunstwinkelfest am 5. September 2026; das Bild hängt dort ein volles Jahr.",
  kw_work_p="„Dies ist eine alte Frau aus Bhaktapur, einer alten Stadt in Nepal. Ihr Gesicht hat mich angezogen — die Falten, der Ausdruck, das graue Haar. Für mich trägt dieses Gesicht ein ganzes Leben voller Geschichten und Erfahrungen. Bhaktapur hat einen ganz eigenen kulturellen Charakter, und ich wollte ein kleines Stück dieser Welt in diesen europäischen Kunstraum bringen.“",
  kw_see_gallery="In der Galerie ansehen",
  kw_how_h="Wie das hier funktioniert",
  kw_how_p="Der Kunstwinkel ist eine dauerhafte Freiluftgalerie an einer Hauswand in der Rathausstraße 23 in Markkleeberg. Jedes Jahr wählt die Stadt 24 eingereichte Werke aus, bringt sie für zwölf Monate an der Wand an und versteigert sie beim Kunstwinkelfest des Folgejahres — der Erlös geht an die Künstlerinnen und Künstler und an das Projekt.",
  kw_f_exh="Ausstellung", kw_f_exh_v="Am Kunstwinkel — Freiluftgalerie, Sammlung 2026/27",
  kw_f_motto="Motto", kw_f_work="Gezeigtes Werk",
  kw_f_unveiled="Enthüllt", kw_f_unveiled_v="5. September 2026, beim 8. Kunstwinkelfest",
  kw_f_until="Zu sehen bis", kw_f_until_v="Kunstwinkelfest 2027",
  kw_f_where="Ort", kw_f_selected="Ausgewählte Werke", kw_f_selected_v="24, von 24 verschiedenen Kunstschaffenden",
  kw_f_org="Veranstalter", kw_f_org_v="Stadt Markkleeberg",
  kw_bid_h="Die Versteigerung läuft noch nicht.",
  kw_bid_p1="Die Sammlung 2026/27 — zu der dieses Bild gehört — wird beim Kunstwinkelfest im September 2027 versteigert. Einige Wochen vorher veröffentlicht die Stadt einen Online-Katalog beim Auktionshaus IKV Fester, in dem schon vor der Live-Auktion Gebote abgegeben werden können.",
  kw_bid_p2="Sobald die Stadt den Link veröffentlicht, steht er hier. Bis dahin:",
  kw_bid_b1="Zum Kunstwinkelfest", kw_bid_b2="Zum Auktionshaus",
  kw_alt_p="Wenn Sie nicht bis zur Versteigerung warten möchten: Srijana hat weitere Originale direkt verfügbar — <a href=\"{gallery}#gallery\">zur Galerie</a> oder <a href=\"mailto:{email}?subject=Bildanfrage\">schreiben Sie ihr</a>.",
  kw_film_kicker="5. September 2026", kw_film_h="Am Tag der Enthüllung",
  kw_film_p="Ein paar Sekunden vom 8. Kunstwinkelfest — die Kamera hebt sich von der Künstlerin zur Wand, wo ihr Bild in der oberen Reihe hängt.",
  kw_film_cap="Srijana Am Kunstwinkel, 5. September 2026.",
  kw_film_fallback="Ihr Browser kann dieses Video nicht abspielen.",
  kw_film_download="Video herunterladen",
  kw_photos_h="Die Enthüllung",
  kw_photos_p="Das 8. Kunstwinkelfest, als die neue Sammlung an die Wand kam.",
  kw_alt_board="Die Wand der Freiluftgalerie Am Kunstwinkel in Markkleeberg mit den 24 neu enthüllten Werken",
  kw_alt_artist_wall="Srijana vor der Kunstwinkel-Wand am Tag der Enthüllung",
  kw_alt_detail="Nahaufnahme der Wand mit „Sanftheit die bleibt“ zwischen den Nachbarwerken",
  kw_alt_lettering="Der Schriftzug Am Kunstwinkel über der angebrachten Sammlung von 24 Werken",
  kw_alt_wide="Die Giebelwand Am Kunstwinkel mit der Freiluftgalerie unter dem Schriftzug",
  kw_alt_artist="Srijana beim Kunstwinkelfest",
  kw_alt_angle="Die Galeriewand von der Seite, darunter das gemalte Seenpanorama",
  kw_alt_artist_full="Srijana unter dem Schriftzug Am Kunstwinkel",
  go_title="Kunstmarkt, Garage Ost Leipzig — Srijana GS",
  go_desc="Srijana GS zeigt und verkauft Originalgemälde an ihrem eigenen Tisch beim Kunstmarkt in der Garage Ost, Leipzig — Samstag, 12. September 2026, 13:00–16:00 Uhr.",
  go_h="Kunstmarkt in der Garage Ost",
  go_lede="Ein Nachmittag in Leipzig, mit den Originalen auf dem Tisch — die Bilder von dieser Website, ein paar Studien, die es nie online geschafft haben, und die Gelegenheit, persönlich über eine Auftragsarbeit zu sprechen.",
  go_poster_alt="Kunstmarkt-Plakat der Garage Ost — ein Marktstand mit Drucken, Keramik und gerahmten Arbeiten",
  go_poster_credit="Veranstaltungsplakat: Garage Ost.",
  go_come_h="Kommen Sie vorbei",
  go_p1="Srijana hat einen eigenen Tisch mit Originalgemälden und kleineren Arbeiten auf Papier. Alles auf dem Tisch ist verkäuflich, ganz ohne Verpflichtung — es ist genauso ein guter Grund, den Pinselstrich aus der Nähe anzusehen, zu fragen, wie ein Bild entstanden ist, oder über ein Porträt aus der eigenen Familie zu sprechen.",
  go_p2="Wenn Sie ein bestimmtes Bild aus der <a href=\"{gallery}#gallery\">Galerie</a> in echt sehen möchten, <a href=\"mailto:{email}?subject=Garage%20Ost%20-%20Bild%20mitbringen%3F\">schreiben Sie vorher kurz</a> — dann bringt sie es mit.",
  go_f_event="Veranstaltung", go_f_event_v="Kunstmarkt — Srijanas Tisch: Originalgemälde, Studien und Drucke",
  go_f_date="Datum", go_f_date_v="Samstag, 12. September 2026",
  go_f_time="Uhrzeit", go_f_time_v="13:00 – 16:00 Uhr",
  go_f_venue="Ort", go_f_addr="Adresse", go_f_addr_v="Hermann-Liebmann-Straße 65–67, 04315 Leipzig",
  go_f_entry="Eintritt", go_f_entry_v="Frei",
  go_f_pay="Bezahlung", go_f_pay_v="Bar oder nach Absprache per Überweisung",
  go_note="<strong>Der Termin ist noch zu bestätigen.</strong> Der Ort steht fest; Datum und Uhrzeit richten sich nach der Ankündigung des Veranstalters. Folgen Sie <a href=\"{insta}\" target=\"_blank\" rel=\"noopener\">@srijana.art.gallery</a> oder <a href=\"mailto:{email}?subject=Garage%20Ost%20Details\">fragen Sie per E-Mail</a>. Die Ankündigung steht auf <a href=\"{listing}\" target=\"_blank\" rel=\"noopener\">rausgegangen.de</a>.",
  go_table_h="Was voraussichtlich auf dem Tisch liegt",
  go_table_medium="Originale · Studien · Drucke",
  go_table_p="Eine Mischung aus den Porträts und den kleineren Aquarellstudien — die Skizzenbuchblätter sind der einfachste Einstieg in eine Sammlung, und vor den großen Acrylporträts bleiben die Leute am längsten stehen.",
  go_browse="Erst die Galerie ansehen",
  imp_title="Impressum — Srijana GS", imp_desc="Impressum für srijana-art.github.io gemäß § 5 DDG.",
  ds_title="Datenschutzerklärung — Srijana GS", ds_desc="Datenschutzerklärung für srijana-art.github.io.",
)
